Verified and added several Cloning overrides in many drivers
OrchardCMS/Orchard pull request #7592
Opened 2017-03-01 11:23 UTC by MatteoPiovanelli-Laser

See issue #7412 

I am not sure all the overrides are correct even here.
I added the Cloning override in some of the drivers that did not have it as well.

2017-03-02 21:06 UTC, sebastienros commented on src/Orchard.Web/Modules/Orchard.Autoroute/Drivers/AutoroutePartDriver.cs
> +            clonePart.CustomPattern = originalPart.CustomPattern;
Is it the actual slug? If so it should be altered.

2017-03-02 21:08 UTC, sebastienros commented
Looks good but we need someone to confirm it works.

/cc summoning @BenedekFarkas

2017-03-02 21:12 UTC, BenedekFarkas commented
I'll be happy to do testing on this and the related PRs, but won't be able to do so in the next few days. I'll add myself as a reviewer just in case, so it shows up for me on GitHub.

2017-03-03 08:12 UTC, MatteoPiovanelli-Laser commented on src/Orchard.Web/Modules/Orchard.Autoroute/Drivers/AutoroutePartDriver.cs
> +            clonePart.CustomPattern = originalPart.CustomPattern;
No. That would be the DisplayAlias property.

2024-11-18 10:40 UTC, BenedekFarkas commented
@MatteoPiovanelli-Laser please merge from dev, I'm testing/reviewing this now. How does this related to #7409 BTW?

2024-11-18 21:06 UTC, BenedekFarkas requested changes

2024-11-18 21:06 UTC, BenedekFarkas commented on src/Orchard.Web/Core/Contents/Controllers/AdminController.cs
> +                return RedirectToRoute(adminRouteValues);
After you merge from dev, please adjust `Core/Contents/Views/Parts.Contents.Clone.SummaryAdmin.cshtml` and `Parts.Contents.Publish.SummaryAdmin.cshtml` (line 29) **not** to include the `ReturnUrl` parameter.

2024-11-18 21:06 UTC, BenedekFarkas commented on src/Orchard.Web/Core/Navigation/Drivers/MenuPartDriver.cs
> +            clonePart.Menu = context.CloneContentItem;
`context.CloneContentItem` causes the "Show on a menu" to always be checked incorrectly.
```suggestion
            clonePart.Menu = originalPart.Menu;
```

2024-11-18 21:06 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.MediaProcessing/Drivers/ImageProfilePartDriver.cs
> +            clonePart.Record.Filters = originalPart.Filters;
Throws YSOD:

> Don't change the reference to a collection with cascade="all-delete-orphan"

Filters are records (and thus references), so they should be cloned too.

2024-11-18 21:06 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.MediaProcessing/Drivers/ImageProfilePartDriver.cs
> +            clonePart.Record.FileNames = originalPart.FileNames;
Do we really need to clone these? Shouldn't this start empty, since the new profile doesn't have any images generated?

2024-11-18 21:06 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Projections/Drivers/NavigationQueryPartDriver.cs
> +            clonePart.QueryPartRecord = originalPart.QueryPartRecord;
Just curious, why is this in Cloned and not Cloning?

2024-11-18 21:06 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Projections/Drivers/QueryPartDriver.cs
> +            clonePart.Record.Layouts = originalPart.Layouts;
Also throws YSOD.

2024-11-18 21:06 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Roles/Drivers/UserRolesPartDriver.cs
> +        }
Should we even allow cloning Users? Do you know of a good use-case here?

2024-11-18 21:06 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Search/Drivers/SearchSettingsPartDriver.cs
> +        }
These are site settings and the Site shouldn't be cloned.

2025-10-05 20:09 UTC, BenedekFarkas commented
@MatteoPiovanelli would you like to continue working on this?

2025-10-10 07:07 UTC, MatteoPiovanelli commented
Sorry, I don't really see that I'll be able to

2025-10-10 20:16 UTC, BenedekFarkas commented
OK, I'll continue in a new PR.

2025-10-10 20:42 UTC, BenedekFarkas commented
See #8854.

2025-10-10 20:42 UTC, closed without merging