Delete and Unpublish buttons in backoffice content edit
OrchardCMS/Orchard pull request #8566
Opened 2022-06-10 14:18 UTC by AndreaPiovanelliLaser

In reference to #8565 
Added unpublish and delete buttons to backoffice content edit view. 
Adapted Orchard.Blogs and Orchard.Widgets to be in line with the patch, adding a "unpublish-button" css class too (it is identical to "publish-button".
Regarding Orchard.Widgets, I removed previous delete button (Widget_DeleteButton shape, Widget.DeleteButton.cshtml) because it was now redundant and conflicted with the Core/Contents... button (not a terrible conflict, but both were displayed and editing the Placement.info turned to be a unreliable solution).
Modified / added actions to controllers when needed.

2022-06-16 17:16 UTC, sebastienros commented on src/Orchard.Web/Core/Contents/Controllers/AdminController.cs
> +        [HttpPost, ActionName("Edit")]
Why is this different that the other unpublish/delete actions?

2022-06-16 17:16 UTC, sebastienros commented on src/Orchard.Web/Core/Contents/Drivers/ContentsDriver.cs
> +                if (part.ContentItem.IsPublished()) {
Maybe put the show/hide logic in the view.

2022-06-16 17:16 UTC, sebastienros commented on src/Orchard.Web/Modules/Orchard.Widgets/Orchard.Widgets.csproj
> +</Project>
Please don't remove the EOLs

2022-06-17 07:47 UTC, AndreaPiovanelliLaser commented on src/Orchard.Web/Core/Contents/Controllers/AdminController.cs
> +        [HttpPost, ActionName("Edit")]
I added delete and unpublish actions referencing specific submits to the controller. There already were unpublish and delete actions (the ones called from the lists), so I called those inside the new actions, specific to the edit form.

2022-06-17 07:50 UTC, AndreaPiovanelli commented on src/Orchard.Web/Core/Contents/Drivers/ContentsDriver.cs
> +                if (part.ContentItem.IsPublished()) {
Removed hide logic from the driver, was already implemented inside the shape too.

2022-06-30 13:34 UTC, AndreaPiovanelliLaser commented
@sebastienros fixed as requested.

2022-07-07 19:15 UTC, sebastienros approved these changes

2022-10-20 17:08 UTC, sebastienros approved these changes

2022-11-17 18:11 UTC, sebastienros commented on src/Orchard.Web/Core/Contents/Drivers/ContentsDriver.cs
> +                if (AdminFilter.IsApplied(System.Web.HttpContext.Current.Request.RequestContext)) {
These drivers are not meant to work on the front-end, so we should not even check if it's the front-end, or then we will start doing it everywhere.

2022-11-17 18:11 UTC, sebastienros commented on src/Orchard.Web/Core/Contents/Drivers/ContentsDriver.cs
> +                results.Add(ContentShape("Content_UnpublishButton", unpublishButton => unpublishButton));
Shouldn't it check there is a published version first?

2022-11-25 14:20 UTC, AndreaPiovanelliLaser commented
Modified the code following Sebastien's remarks.

2022-12-01 18:15 UTC, sebastienros approved these changes

2024-04-16 18:05 UTC, BenedekFarkas requested changes
I really like the consolidation for the delete button! Please merge from 1.10.x.

However I'm unsure about adding the Unpublish button in the editor - is that really necessary UX-wise? I feel like it get can get a bit too crowded in the action button row.

Some of the editors I checked have minor styling issues under different circumstances, but some of those might be independent of this PR:

1. BlogPost, Page, etc., when Draftable is enabled (default configuration) - too much space
![image](https://github.com/OrchardCMS/Orchard/assets/2797449/1b3023fa-8f3d-41af-bffe-9f40fd2051b8)
2. BlogPost, when Draftable is disabled - spacing missing:
![image](https://github.com/OrchardCMS/Orchard/assets/2797449/a8734f96-eb20-4831-ab0b-f01e9f5e62f7)

EDIT: These spacing problems are addressed by my suggestions below.

2024-04-16 18:05 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Blogs/Controllers/BlogPostAdminController.cs
> +        public ActionResult EditDeletePOST (int blogId, int postId, string returnUrl) {
```suggestion
        public ActionResult EditDeletePOST(int blogId, int postId, string returnUrl) {
```

2024-04-16 18:05 UTC, BenedekFarkas commented on src/Orchard.Web/Core/Contents/Views/Content.DeleteButton.cshtml
> +}
```suggestion
}

```

2024-04-16 18:05 UTC, BenedekFarkas commented on src/Orchard.Web/Core/Contents/Views/Content.UnpublishButton.cshtml
> +}
```suggestion
}

```

2024-04-16 18:05 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Widgets/Drivers/WidgetPartDriver.cs
> +            if (widgetPart.Id > 0 && widgetPart.TypeDefinition.Settings.GetModel<ContentTypeSettings>().Draftable) {
Being able to unpublish does/should not depend on Draftable.
```suggestion
            if (widgetPart.Id > 0) {
```

2024-04-16 18:05 UTC, BenedekFarkas commented on src/Orchard.Web/Core/Contents/Views/Content.UnpublishButton.cshtml
> +@if (Authorizer.Authorize(Permissions.PublishContent, (IContent)Model.ContentItem) && ((IContent)Model.ContentItem).IsPublished()) {
```suggestion

@{
    var contentItem = Model.ContentItem as IContent;
}

@if (contentItem.IsPublished() && Authorizer.Authorize(Permissions.PublishContent, contentItem)) {
```

2024-04-16 18:05 UTC, BenedekFarkas commented on src/Orchard.Web/Core/Contents/Drivers/ContentsDriver.cs
> +                }
Re: [the previous comment](https://github.com/OrchardCMS/Orchard/pull/8566#discussion_r899343079) - shouldn't be just this then, since the template already checks `IsPublished`?
```suggestion
                results.Add(ContentShape("Content_UnpublishButton", unpublishButton => unpublishButton));
```

2024-05-16 07:58 UTC, MatteoPiovanelli-Laser commented on src/Orchard.Web/Core/Contents/Drivers/ContentsDriver.cs
> +                }
I don't remember right now. I'll check asap.

2024-05-16 07:58 UTC, MatteoPiovanelli-Laser commented
rebased on 1.10.x and applied some of @BenedekFarkas  suggestions

2024-09-03 17:17 UTC, BenedekFarkas commented
Sorry for replying just now, I'll be able to review later towards the end of September (after Harvest).

2024-11-15 13:07 UTC, BenedekFarkas requested changes

2024-11-15 13:07 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Blogs/Controllers/BlogPostAdminController.cs
Please use remove and sort usings and auto-formatting.

2024-11-15 13:07 UTC, BenedekFarkas commented on src/Orchard.Web/Core/Contents/Views/Content.DeleteButton.cshtml
> +@using Orchard.Utility.Extensions
Unused using.

2024-11-15 13:07 UTC, BenedekFarkas commented on src/Orchard.Web/Core/Contents/Views/Content.UnpublishButton.cshtml
> +@using Orchard.Utility.Extensions;
Unused using.

2024-11-15 13:07 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Widgets/Drivers/WidgetPartDriver.cs
> +            if (widgetPart.Id > 0 && widgetPart.TypeDefinition.Settings.GetModel<ContentTypeSettings>().Draftable) {
This is not addressed.

2024-11-15 13:07 UTC, BenedekFarkas commented on src/Orchard.Web/Core/Contents/Views/Content.UnpublishButton.cshtml
> +}
Add empty lines around this block. I pointed this out earlier too and it would be easier if you just accepted my change suggestions in bulk, so that I don't have to go through all of them again to figure out what's fixed and what isn't.

```suggestion

@{
    var contentItem = Model.ContentItem as IContent;
}

```

2024-11-15 13:07 UTC, BenedekFarkas commented on src/Orchard.Web/Core/Contents/Drivers/ContentsDriver.cs
> +                }
The `Content.UnpublishButton` template _does_ check if the item is published.

2024-11-15 13:07 UTC, BenedekFarkas commented on src/Orchard.Web/Core/Contents/Placement.info
> +    <Place Content_DeleteButton="Sidebar:22"/>
Reordered them according to placement. Also `Content_DeleteButton` shouldn't be the first one, because it will be become the default action (e.g., when you hit enter while editing the title) just by virtue of being the first in the rendered HTML.
SaveButton should come first, then PublishButton (because SaveButton is not rendered if the type is not Draftable).

```suggestion
    <Place Content_SaveButton="Sidebar:23"/>
    <Place Content_PublishButton="Sidebar:24"/>
    <Place Content_UnpublishButton="Sidebar:25"/>
    <Place Content_DeleteButton="Sidebar:26"/>
```

2024-11-15 13:07 UTC, BenedekFarkas commented on src/Orchard.Web/Themes/TheAdmin/Styles/site.css
>      border-right:1px solid #ccc;
This styling was overcomplicated to begin with, but we don't need to complicate it further. You can apply this to the whole section between lines 1128 and 1147, so we don't need to care about how many items are rendered and in what order:

```css
.edit-item-sidebar fieldset {
    margin: 0;
    padding: 0;
    clear: none;
    float: left;
}
.edit-item-sidebar fieldset:not(:first-child) {
    margin-left: 12px;
}
.edit-item-sidebar fieldset:first-child {
    clear: left;
}
fieldset.publish-button, fieldset.unpublish-button {
    padding-right: 12px;
    border-right: 1px solid #ccc;
}
fieldset.delete-button {
    float: right;
}
```

2024-11-15 13:07 UTC, BenedekFarkas commented on src/Orchard.Web/Themes/TheAdmin/Styles/site.css
> -.dir-rtl fieldset.publish-button, fieldset.delete-button, .dir-rtl fieldset.save-button {
Same as above, RTL version for lines 1498-1509:

```css
.dir-rtl .edit-item-sidebar fieldset {
    float: right;
}
.dir-rtl .edit-item-sidebar fieldset:first-child {
    clear: right;
}
.dir-rtl .edit-item-sidebar fieldset:not(:first-child) {
    margin-left: 0;
    margin-right: 12px;
}
.dir-rtl fieldset.publish-button, fieldset.unpublish-button {
    padding-right: 0;
    border-right: none;
    padding-left: 12px;
    border-left: 1px solid #ccc;
}
.dir-rtl fieldset.delete-button {
    float: left;
}
```

2024-11-15 13:07 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Widgets/Drivers/WidgetPartDriver.cs
> +            }
This is already rendered by ContentsDriver.
```suggestion
```

2025-01-14 21:42 UTC, BenedekFarkas commented
@AndreaPiovanelli please let me know if you want to keep working on this PR until next week, otherwise I'll finish this in a new PR using the changes from here.

2025-01-17 08:18 UTC, AndreaPiovanelli commented
> @AndreaPiovanelli please let me know if you want to keep working on this PR until next week, otherwise I'll finish this in a new PR using the changes from here.

Since it's a very old request from a customer that never went online, we are not working on it anymore.

2025-01-23 11:22 UTC, BenedekFarkas commented
@AndreaPiovanelli so are you working on this? Let me know if it's ready for review.

2025-01-23 11:26 UTC, AndreaPiovanelli commented
> @AndreaPiovanelli so are you working on this? Let me know if it's ready for review.

I was addressing the refactoring and changes you requested and merging the latest 1.10.x to the pr branch. It should be done, now.

2025-06-05 20:06 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Blogs/Controllers/BlogPostAdminController.cs
Auto-formatting is still needed (I can't push to your PR branch).

2025-06-05 20:26 UTC, BenedekFarkas requested changes

2025-06-05 20:26 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Widgets/Drivers/LayerPartDriver.cs
Please apply auto-formatting in this file too.

2025-06-05 20:26 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Blogs/Controllers/BlogPostAdminController.cs
Auto-formatting is still needed (I can't push to your PR branch).

2025-06-05 21:08 UTC, BenedekFarkas requested changes
Minor changes suggested, otherwise LGTM!

2025-06-05 21:08 UTC, BenedekFarkas commented on src/Orchard.Web/Themes/TheAdmin/Styles/site.css
>  }
I had this idea before my previous suggestion, so I should've written this instead: It would be a lot easier to just add the separator between every item - that way we don't need to worry about the number of items rendered (which can vary based on the content definition):

```css
.edit-item-sidebar fieldset {
    margin: 0;
    padding: 0;
    clear: none;
    float: left;
}

.edit-item-sidebar fieldset:not(:first-child):not(.delete-button) {
    margin-left: 12px;
    padding-left: 12px;
    border-left: 1px solid #ccc;
}

.edit-item-sidebar fieldset.delete-button {
    float: right;
}
```

2025-06-05 21:08 UTC, BenedekFarkas commented on src/Orchard.Web/Themes/TheAdmin/Styles/site.css
>  }
RTL version of the above:

```css
.dir-rtl .edit-item-sidebar fieldset {
    float: right;
}

.dir-rtl .edit-item-sidebar fieldset:not(:first-child):not(.delete-button) {
    margin-left: 0;
    padding-left: 0;
    border-left: none;
    margin-right: 12px;
    padding-right: 12px;
    border-right: 1px solid #ccc;
}

.dir-rtl .edit-item-sidebar fieldset.delete-button {
    float: left;
}
```

2025-06-13 12:58 UTC, AndreaPiovanelli commented
After merging 1.10.x again inside the branch and applying the style corrections suggested by @BenedekFarkas , looks good imho:
![image](https://github.com/user-attachments/assets/3598c777-6872-44e2-a626-cb84f0ca89d0)

2025-06-13 14:12 UTC, BenedekFarkas approved these changes

2025-06-13 14:16 UTC, BenedekFarkas commented
Yup yup, that's exactly what it should look like!

2025-06-13 14:17 UTC, merged