Upgrade/datetimefield format
OrchardCMS/Orchard pull request #8729
Opened 2023-10-30 14:31 UTC by AgostiniAlessandro

Issue #8728

Added the AllowDisplayOptionsOverride property in DateTimeFieldSetting.

Handled this setting in DateTimeField so that it returns the overriding value (if set) or (if there's no overriding value set) the setting value.

Handles a new case in in DefaultDateLocalizationServices.cs: when converting a DateTime to and from UTC with the IgnoreDate setting, if the DateTime had a valid Date (!= DateTime.min) the code was returning a wrong value since it didn't handle the solar time correctly. 
Probably this case wasn't handled correctly since DateTimeFields were only allowing the user to insert the time when their Display property was set to TimeOnly, but we decided to show both the Date and Time editors when the AllowDisplayOptionsOverride is set to true so now it's possibile to have to convert DateTime with a valid date and the IgnoreDate option set to true.

2023-10-30 15:52 UTC, AgostiniAlessandro commented
2 tests failed but when I tried to rerun them locally I got no problem. Also, since the tests that failed don't have nothing to do with the files I worked on I guess there was some problem running the test, probably some connection issues. 

Here is the code for the two tests that are failing:

        [Test]
        public void StatusCodeShouldBe404ForUnexistingResources() {
            var download = _webDownloader.Download("http://orchardproject.net/yepyep");
            Assert.That(download, Is.Not.Null);
            Assert.That(download.StatusCode, Is.EqualTo(HttpStatusCode.NotFound));
            Assert.That(download.Content, Is.Null);
        }

        [Test]
        public void StatusCodeShouldBe200ForValidRequests() {
            var download = _webDownloader.Download("http://orchardproject.net/");
            Assert.That(download, Is.Not.Null);
            Assert.That(download.StatusCode, Is.EqualTo(HttpStatusCode.OK));
            Assert.That(download.Content, Is.Not.Empty);
        }

2024-11-18 21:24 UTC, BenedekFarkas commented
Indeed, the test failures were caused by the domain being unreachable, I've fixed that since then. Please merge from 1.10.x.

2024-11-18 23:45 UTC, BenedekFarkas requested changes
If you agree with the suggestions, please be sure to commit them from the UI in bulk (= one commit), so that the corresponding conversation is also resolved, then proceed with follow-up changes (due to property name changes), if necessary.

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Fields/DateTimeField.cs
> +using System.Runtime.InteropServices.WindowsRuntime;
```suggestion
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Fields/DateTimeField.cs
> +using Orchard.UI.Notify;
```suggestion
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Fields/DateTimeField.cs
>                  var settings = this.PartFieldDefinition.Settings.GetModel<DateTimeFieldSettings>();
```suggestion
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Fields/DateTimeField.cs
>                  var settings = this.PartFieldDefinition.Settings.GetModel<DateTimeFieldSettings>();
```suggestion
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Drivers/DateTimeFieldDriver.cs
> +                }
```suggestion
                }
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Drivers/DateTimeFieldDriver.cs
> +
```suggestion
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Drivers/DateTimeFieldDriver.cs
> +
Simplified together with the code below.
```suggestion
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Drivers/DateTimeFieldDriver.cs
> +            }
```suggestion
                // Show both the date and time editor if the override is enabled, so that changing the behavior for the
                // given content item doesn't require saving it twice.
                var showDate = settings.AllowDisplayOptionOverride
                    || settings.Display == DateTimeFieldDisplays.DateAndTime
                    || settings.Display == DateTimeFieldDisplays.DateOnly;
                var showTime = settings.AllowDisplayOptionOverride
                    || settings.Display == DateTimeFieldDisplays.DateAndTime
                    || settings.Display == DateTimeFieldDisplays.TimeOnly;
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/ViewModels/DateTimeFieldViewModel.cs
> +        public bool AllowDisplayOptionsOverride { get; set; }
Use singular name.
```suggestion
        public bool AllowDisplayOptionOverride { get; set; }
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/ViewModels/DateTimeFieldViewModel.cs
> +
```suggestion
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Views/EditorTemplates/Fields/DateTime.Edit.cshtml
> +
```suggestion
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Drivers/DateTimeFieldDriver.cs
> +
```suggestion
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Drivers/DateTimeFieldDriver.cs
> +                }
```suggestion
                var showDate = field.Display == DateTimeFieldDisplays.DateAndTime || field.Display == DateTimeFieldDisplays.DateOnly;
                var showTime = field.Display == DateTimeFieldDisplays.DateAndTime || field.Display == DateTimeFieldDisplays.TimeOnly;
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Drivers/DateTimeFieldDriver.cs
> +                .Enumerate<DateTimeField>(() => field => new[] { field.DateTime });
```suggestion
                .Enumerate<DateTimeField>(() => field => new[] { field.DateTime });
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Settings/DateTimeFieldSettings.cs
> +        public bool AllowDisplayOptionsOverride { get; set; }
```suggestion
        public bool AllowDisplayOptionOverride { get; set; }
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Settings/DateTimeFieldEditorEvents.cs
> +                builder.WithSetting("DateTimeFieldSettings.AllowDisplayOptionsOverride", model.AllowDisplayOptionsOverride.ToString(CultureInfo.InvariantCulture));
```suggestion
                builder.WithSetting("DateTimeFieldSettings.AllowDisplayOptionOverride", model.AllowDisplayOptionsOverride.ToString(CultureInfo.InvariantCulture));
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Views/EditorTemplates/Fields/DateTime.Edit.cshtml
> +    @if (Model.AllowDisplayOptionsOverride) {
```suggestion
    @if (Model.AllowDisplayOptionOverride) {
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Fields/DateTimeField.cs
> +            }
```suggestion
            get => Storage.Get<string>("DisplayOption");
            set => Storage.Set("DisplayOption", value ?? string.Empty);
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Fields/DateTimeField.cs
> +            }
```suggestion
            set => DisplayOption = value.ToString();
```

2024-11-18 23:45 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Fields/Fields/DateTimeField.cs
>                  return settings.Display;
```suggestion
                return settings.AllowDisplayOptionOverride && Enum.TryParse(DisplayOption, out DateTimeFieldDisplays displayOption)
                    ? displayOption
                    : settings.Display;
```

2024-11-21 18:20 UTC, closed without merging