Exclude ContentWidgets layer by default in order to increase performance
OrchardCMS/Orchard pull request #8750
Opened 2024-01-24 07:46 UTC by gdessimoneinvalle

In reference to #8749

Added a filter to exlude widgets from list if the layer ContentWidgets is not explicity chosen by the user in order to open the widget page more quickly

2024-01-25 18:07 UTC, sebastienros commented
@MatteoPiovanelli-Laser

2024-02-19 20:10 UTC, BenedekFarkas requested changes

2024-02-19 20:10 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Widgets/Controllers/AdminController.cs
>              string zonePreviewImage = _virtualPathProvider.FileExists(zonePreviewImagePath) ? zonePreviewImagePath : null;
```suggestion
            var zonePreviewImagePath = string.Format("{0}/{1}/ThemeZonePreview.png", currentTheme.Location, currentTheme.Id);
            var zonePreviewImage = _virtualPathProvider.FileExists(zonePreviewImagePath) ? zonePreviewImagePath : null;
```

2024-02-19 20:10 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Widgets/Controllers/AdminController.cs
> +            }
Simplified logic with corrected variable naming.
```suggestion
            // Only listing the widgets of the "ContentWidgets" layer when it's explicitly chosen, not by default (for
            // performance reasons).
            IEnumerable<WidgetPart> widgets;
            var contentWidgetsLayer = layers.Where(x => x.Name.ToLowerInvariant() == "contentwidgets").FirstOrDefault();
            if (contentWidgetsLayer == null) {
                widgets = _widgetsService.GetWidgets();
            }
            else { // The "ContentWidgets" layer exists.
                var layerIds = layers.Select(x => x.Id).ToList();
                // There's no layer selected or it's not "ContentWidgets", so excluding it from the widget listing.
                if (!layerId.Equals(contentWidgetsLayer.Id)) {
                    layerIds.Remove(contentWidgetsLayer.Id);
                }

                widgets = _widgetsService.GetWidgets(layerIds.ToArray());
            }
```

2024-02-19 20:10 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Widgets/Controllers/AdminController.cs
> +
```suggestion
```

2024-02-19 20:21 UTC, BenedekFarkas commented
When/what creates the ContentWidgets layer? On latest 1.10.x, I added a content widget to the home page, but there was no ContentWidgets layer created and I couldn't find any reference to other than this code.

2024-02-21 10:26 UTC, MatteoPiovanelli-Laser commented
> When/what creates the ContentWidgets layer? On latest 1.10.x, I added a content widget to the home page, but there was no ContentWidgets layer created and I couldn't find any reference to other than this code.

It's created by a feature. I think that's an issue with this PR. The optimization makes sense to me, because we also sometimes generate layers/widgets dynamically.
But the list of layers that are "filtered out" should be set in a Settings, rather than hardcoded, I think.

2024-02-21 11:02 UTC, BenedekFarkas commented
OK, but which feature and where? I can't find any clue to this layer existing in the code.

2024-02-21 13:18 UTC, MatteoPiovanelli-Laser commented
One of our own features (hence it wouldn't be in this repo) adds a layer with that same name, so it's likely to be that one. That feature can easily lead to having many widgets.

2024-02-21 13:33 UTC, BenedekFarkas commented
In that case this code cannot be accepted like this.

Out of curiosity, how many Content Widgets are we talking about? Isn't the performance issue a SELECT N+1 for each of them? Maybe it's an inherent issue with Content Widgets we can address.

2024-02-22 08:53 UTC, MatteoPiovanelli-Laser commented
Can be a few widgets, but it's easily hundreds. The feature lets you add widgets that are specific to specific ContentItems.
In the BO page that displays all widgets, I don't think we have an N+1 issue, because the queries are those from the Orchard.Widgets Controller/service, that simply gets all Widgets. 
It becomes a potential performance bottleneck when it fetches all those widgets (each one being a contentitem), fires off all their handlers, then renders them out (grouping them by zone and layer, if I remember correctly).

2024-02-26 17:49 UTC, BenedekFarkas commented
OK, thanks! I'll close this PR, but we can discuss under the issue if there's an Orchard-specific improvement that can help in this case too - I have an idea.

2024-02-26 17:49 UTC, closed without merging