Ambiguity in LocalizedTaxonomyController action names
OrchardCMS/Orchard pull request #8785
Opened 2024-04-16 07:18 UTC by AndreaPiovanelli

This fixes an ambiguity issue for the GetTaxonomy action of LocalizedTaxonomyController. There was a "new GetTaxonomy" action in AdminLocalizedTaxonomyController too that was ambiguous, failing to properly work. For this reason, the action has been removed from AdminLocalizedTaxonomyController and the admin filter is added via override of the ApplyPreRequest function.

2024-04-16 14:35 UTC, BenedekFarkas commented
Can you provide repro steps to compare before/after?

2024-04-17 07:29 UTC, AndreaPiovanelli commented
> Can you provide repro steps to compare before/after?

The issue was easily reproducible when opening the edit page of an item containing a TaxonomyField. The ajax call in TaxonomyFieldList shape (https://github.com/LaserSrl/Orchard/blob/8ed7b67f1fc865e60b1de658b085fb49efb45151/src/Orchard.Web/Modules/Orchard.Taxonomies/Views/EditorTemplates/Fields/TaxonomyFieldList.cshtml#L13) failed, showing the "Loading taxonomy failed" alert message at line 136 of the same file. The error wasn't logged by Orchard, because it's a MVC error, but you can see it in the browser console:
Loading taxonomy fail message:
![image](https://github.com/OrchardCMS/Orchard/assets/83577153/f7411b54-ce65-41c0-9d29-225e89a0311f)
The error displayed was the following:
The current request for action 'GetTaxonomy' on controller type 'AdminLocalizedTaxonomyController' is ambiguous between the following action methods:

> The current request for action 'GetTaxonomy' on controller type 'AdminLocalizedTaxonomyController' is ambiguous between the following action methods:
> System.Web.Mvc.ActionResult GetTaxonomy(System.String, System.String, Int32, System.String, System.String) on type Orchard.Taxonomies.Controllers.AdminLocalizedTaxonomyController
> System.Web.Mvc.ActionResult GetTaxonomy(System.String, System.String, Int32, System.String, System.String) on type Orchard.Taxonomies.Controllers.LocalizedTaxonomyController

I didn't notice this problem before PR #8780 was merged, because of the javascript syntax error blocking the proper execution of the code.

2024-04-17 08:20 UTC, BenedekFarkas requested changes
Two small things noted, otherwise works great!

2024-04-17 08:20 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/LocalizedTaxonomyController.cs
> +        }
```suggestion
        protected virtual void ApplyPreRequest() { }
```

2024-04-17 08:20 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/LocalizedTaxonomyController.cs
Please apply automatic formatting and usings cleanup in both this and `AdminLocalizedTaxonomyContoller`.

2024-04-17 09:08 UTC, AndreaPiovanelli commented on src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/LocalizedTaxonomyController.cs
Autoformatting and cleanup should be ok in last commit (https://github.com/OrchardCMS/Orchard/pull/8785/commits/2f6ada44cf1ad56d34a2f86d59d2b4f1a81ec13f)

2024-04-17 09:23 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/LocalizedTaxonomyController.cs
Great, thanks!

2024-04-17 09:51 UTC, BenedekFarkas requested changes

2024-04-17 09:51 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/AdminLocalizedTaxonomyController.cs
> +﻿using System.Web.Routing;
Actually, I just realized I misread the class names, but with `AdminLocalizedTaxonomyController` deriving from `LocalizedTaxonomyController`, this whole thing can be made a lot easier with proper inheritance. All the suggestions need to be applied together for them to work.
```suggestion
﻿using System.Web.Mvc;
﻿﻿using System.Web.Routing;
```

2024-04-17 09:51 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/AdminLocalizedTaxonomyController.cs
> +        protected override void ApplyPreRequest() {
```suggestion
        [OutputCache(NoStore = true, Duration = 0)]
        public override ActionResult GetTaxonomy(string contentTypeName, string taxonomyFieldName, int contentId, string culture, string selectedValues) {
            AdminFilter.Apply(_requestContext);
```

2024-04-17 09:51 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/AdminLocalizedTaxonomyController.cs
>              AdminFilter.Apply(_requestContext);
```suggestion
            return base.GetTaxonomy(contentTypeName, taxonomyFieldName, contentId, culture, selectedValues);
```

2024-04-17 09:51 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/LocalizedTaxonomyController.cs
> +        protected virtual void ApplyPreRequest() { }
```suggestion
```

2024-04-17 09:51 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/LocalizedTaxonomyController.cs
> +            ApplyPreRequest();
```suggestion
```

2024-04-17 09:51 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/LocalizedTaxonomyController.cs
>          public ActionResult GetTaxonomy(string contentTypeName, string taxonomyFieldName, int contentId, string culture, string selectedValues) {
```suggestion
        public virtual ActionResult GetTaxonomy(string contentTypeName, string taxonomyFieldName, int contentId, string culture, string selectedValues) {
```

2024-05-07 16:59 UTC, BenedekFarkas commented
@AndreaPiovanelli please check the suggested changes and/or enable edits from maintainers.

2024-05-16 13:48 UTC, AndreaPiovanelli commented
@BenedekFarkas I took some time to test your suggestions in our environment and have now applied the changes you requested to current pr branch. 
I had to apply the last one separatedly (not via the "commit suggestion" button) because git disabled that button as apparently it was an "outdated suggestion" for it.

2024-05-16 15:10 UTC, BenedekFarkas commented
OK, thanks!

2024-05-16 15:16 UTC, BenedekFarkas approved these changes

2024-05-16 15:16 UTC, merged