Fix to import Vimeo videos
OrchardCMS/Orchard pull request #8804
Opened 2024-09-18 09:32 UTC by AndreaPiovanelli

In reference to #8803 , added a fix to avoid the scraping of the "vimeo.com/xxxx" page (which replies with a 429 http error) by forcing the direct api call if Vimeo domain is recognized.

2024-10-03 17:06 UTC, sebastienros commented
I think this is really wrong. If Vimeo doesn't support OEmbed then it's better to have another feature dedicated to vimeo, or just drop vimeo support altogether.

2024-10-18 08:16 UTC, AndreaPiovanelli commented
> I think this is really wrong. If Vimeo doesn't support OEmbed then it's better to have another feature dedicated to vimeo, or just drop vimeo support altogether.

Vimeo still supports embed (and the xml format is still the same) but it doesn't include the link to the video metadata xml in its markup anymore, so it cannot be automatically imported by directly reading the video page content.

While investigating further, we also noticed Youtube stopped working too. This is caused by the fact it blocks video output when trying to watch a video from a server (a bot protection). This is what happened when I tried to debug the Youtube issue directly from the server: I was trying to find a way to get the meta link in the page, but that's what the page shows:
![image](https://github.com/user-attachments/assets/fd214dae-3872-4313-ae12-bccb69137710)

For this reason, we worked on a patch on the code, similar to what has already been done to get Vimeo's oembed xml data: to properly get the provider, we check for the url we're redirected to and, with that information, call the right api.

2024-11-19 23:43 UTC, BenedekFarkas requested changes

2024-11-19 23:43 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/OEmbedController.cs
```suggestion
```

2024-11-19 23:43 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/OEmbedController.cs
> +                                // bubble exception
```suggestion
                                throw;
```

2024-11-19 23:43 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/OEmbedController.cs
> +                } else if (youtube) {
```suggestion
                }
                else if (youtube) {
```

2024-11-19 23:43 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/OEmbedController.cs
> +                } else {
```suggestion
                }
                else {
```

2024-11-19 23:43 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/OEmbedController.cs
> +                            } catch {
```suggestion
                            }
                            catch {
```

2024-11-19 23:43 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/OEmbedController.cs
> +            } catch {
```suggestion
            }
            catch {
```

2024-11-19 23:43 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/OEmbedController.cs
> +            } else {
```suggestion
            }
            else {
```

2024-11-19 23:43 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/OEmbedController.cs
> +            } else {
```suggestion
            }
            else {
```

2024-11-19 23:43 UTC, BenedekFarkas commented on src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/OEmbedController.cs
> +            myHttpWebResponse.Close();
```suggestion
            var myHttpWebRequest = WebRequest.Create(myUri) as HttpWebRequest;
            // Send the request and wait for response.
            using (var myHttpWebResponse = myHttpWebRequest.GetResponse() as HttpWebResponse) {
                if (!myUri.Equals(myHttpWebResponse.ResponseUri)) {
                    myUri = myHttpWebResponse.ResponseUri;
                }
            }
```

2024-11-19 23:44 UTC, BenedekFarkas commented
> > I think this is really wrong. If Vimeo doesn't support OEmbed then it's better to have another feature dedicated to vimeo, or just drop vimeo support altogether.
> 
> Vimeo still supports embed (and the xml format is still the same) but it doesn't include the link to the video metadata xml in its markup anymore, so it cannot be automatically imported by directly reading the video page content.
> 
> While investigating further, we also noticed Youtube stopped working too. This is caused by the fact it blocks video output when trying to watch a video from a server (a bot protection). This is what happened when I tried to debug the Youtube issue directly from the server: I was trying to find a way to get the meta link in the page, but that's what the page shows: ![image](https://private-user-images.githubusercontent.com/83577153/377777755-fd214dae-3872-4313-ae12-bccb69137710.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjAwOTMsIm5iZiI6MTczMjA1OTc5MywicGF0aCI6Ii84MzU3NzE1My8zNzc3Nzc3NTUtZmQyMTRkYWUtMzg3Mi00MzEzLWFlMTItYmNjYjY5MTM3NzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDIzNDMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZjI3YzYwYTI5ZDQ5YjM4MjFlMDcyNDYyM2RiOGEyMWUwMmEzODFjYzY0YjdkMGQ3NzcwNzM5YTc0OTExOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kiel2cDrXrV-o7R-G2FgEp3-r6l7DJT13WRjC6xkjsM)
> 
> For this reason, we worked on a patch on the code, similar to what has already been done to get Vimeo's oembed xml data: to properly get the provider, we check for the url we're redirected to and, with that information, call the right api.

@sebastienros what do you think? BTW I tested the YouTube import (but couldn't test Vimeo), works fine.

2024-11-21 18:39 UTC, sebastienros commented
Let's keep oembed as is, it's oembed. Add some other option called youtube, another one for vimeo and they are dedicated. Or a single one called "video" which would support whatever we want. Copy as much as you want from the current oembed.

2025-01-17 16:08 UTC, AndreaPiovanelli commented
@sebastienros what if we start from here: https://github.com/OrchardCMS/Orchard/blob/d26e8e47f132b1fb210e244735ec755d9d948df7/src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/OEmbedController.cs#L85
And we implement a new service that does the job of getting the href variable (used at line 98 of the same class).
This enable us to implement dedicated services for Vimeo and Youtube cases while keeping the Media Library as a reference (and possibly the service we implement inside Media Library as a base class to fallback to).

2025-01-23 18:11 UTC, sebastienros commented
Sounds good

2025-01-27 10:36 UTC, AndreaPiovanelli commented
> Sounds good

To have a cleaner situation, I created a new pr: #8827

2025-01-27 10:41 UTC, closed without merging